### PR TITLE
Readout

### PR DESCRIPTION
**Pull request by MikelElorza**
No he conseguido poner un path general para apuntar a la carpeta de dropbox en la nube. Se podria definir esta ubicacion en una variable de entorno, como tu decias, pero no se si no es mas facil poner la ubicación de la carpeta directamente en el notebook en LaserLabp. 
Hay que escribir a mano la ubicacion de la carpeta para que el programa funcione.  A partir de ahi, el programa deberia valer para todos.

He eliminado tambien la dependencia de ATools ya que me da problemas que no he conseguido solucionar.

### CODE REVIEW

**Comment by jjgomezcadenas** [comment]
Good job Mikel.
1. Write in English. The project may become in the future bigger than you think.
2. Investigate what happens with ATools, we need them.
3. THe solution you have implemented is not good. It implies that each user has a divergent notebook (because the initial address is dependent of the user). Thus, is definitively not more easy, but more difficult. Add environment variable JLaserData pointing to the root of your (local) directory. We will assume that every use has the same directory structure (which is reasonable). 
4. Add a test. Once you point to the root, you expect to see this:
"""
FLUORI               Setup                pdata
Icon?                analysis             results
LabBook              data
Portada7K_Juanjo.pdf docs
"""
Your test should list the directory and check that "data" and "pdata" are present.

**Comment by MikelElorza** [comment]
I have added ATools to my Pkg registries.
The location of the dropbox folder must be stored in the enviroment variable "JLaserData".

**Comment by jjgomezcadenas** [comment]
Very good. Now add a a few tests in the NB. Use the julia file system
https://docs.julialang.org/en/v1/base/file/

To list the files under JLaserData, and check that data and pdata appear there.

**Comment by MikelElorza** [comment]
I have just added some tests to check that data, pdata and Fluri are there

**Comment by jjgomezcadenas** [comment]
I see that you have included the tests. Now go to:

$JBoldLab/Projects/BoldLab/test (be sure to define $BoldLab pointing to the root of your BoldLab project) and add the tests of your NB (without removing from NB) to runtests.jl. Then ensure that tests pass:

> julia
> pkg Activate "."
> test

Then commit and update the PR

**Comment by jjgomezcadenas** [comment]
See my prvious comment. Pass your tests now to the test file.

**Comment by MikelElorza** [comment]
Tests written and passed!

**Comment by jjgomezcadenas** [comment]
The remote run fails due to problems with ATOOLs, let me investigate.

**Pull request merged**
